array = [
    {
        "name": "SHFE.rb2305",
        "frequency": "180s",
        "count": "560",
        "refresh": "true",
        "sleep": 180 / 3,
    },
    {
        "name": "SHFE.rb2305",
        "frequency": "900s",
        "count": "560",
        "refresh": "true",
        "sleep": 900 / 3,
    },
    {
        "name": "SHFE.rb2305",
        "frequency": "3600s",
        "count": "560",
        "refresh": "true",
        "sleep": 3600 / 3,
    },
    {
        "name": "CZCE.MA305",
        "frequency": "180s",
        "count": "560",
        "refresh": "true",
        "sleep": 180 / 3,
    },
    {
        "name": "CZCE.MA305",
        "frequency": "900s",
        "count": "560",
        "refresh": "true",
        "sleep": 900 / 3,
    },
    {
        "name": "CZCE.MA305",
        "frequency": "3600s",
        "count": "560",
        "refresh": "true",
        "sleep": 3600 / 3,
    },
    {
        "name": "DCE.m2305",
        "frequency": "180s",
        "count": "560",
        "refresh": "true",
        "sleep": 180 / 3,
    },
    {
        "name": "DCE.m2305",
        "frequency": "900s",
        "count": "560",
        "refresh": "true",
        "sleep": 900 / 3,
    },
    {
        "name": "DCE.m2305",
        "frequency": "3600s",
        "count": "560",
        "refresh": "true",
        "sleep": 3600 / 3,
    },
]

fields = [
    "time",
    "open",
    "high",
    "low",
    "close",
    "date",
    "name",
    "level",
    "closeGt",
    "closeLt",
    "closeGtDiff",
    "closeLtDiff",
]
